export const CHESSORT_STATCOUNTER_PROJECT = import.meta.env.VITE_CHESSORT_STATCOUNTER_PROJECT;
export const CHESSORT_STATCOUNTER_SECURITY = import.meta.env.VITE_CHESSORT_STATCOUNTER_SECURITY;
export const CHESSORT_GA_TRACKING_ID = import.meta.env.VITE_CHESSORT_GA_TRACKING_ID;
